Feat : Navigation for desktop (simple).
shuklahimanshu81/Blossom-UI pull request #10
Opened 2022-02-11 10:35 UTC by shuklahimanshu81

![Screenshot (341)](https://user-images.githubusercontent.com/70198636/153576668-bfe2c853-edfe-4f54-bc31-6b829ded9046.png)

2022-02-11 10:52 UTC, FarhanMobashir requested changes
go through the comment

2022-02-11 10:52 UTC, FarhanMobashir commented on components/Navigation/Navigation.css
> +    z-index: 1;
why z-index for fav ?

2022-02-11 10:54 UTC, shuklahimanshu81 commented on components/Navigation/Navigation.css
> +    z-index: 1;
It was going below fav icon without z-index.

2022-02-11 10:56 UTC, FarhanMobashir commented on components/Navigation/Navigation.css
> +    z-index: 1;
Alright. I think you can use the badge fro the component library that you've made. That will be quite easy

2022-02-11 14:26 UTC, shuklahimanshu81 commented on components/Navigation/Navigation.css
> +    z-index: 1;
Thanks for pointing out, made the changes . Have a look again pls.

2022-02-11 14:29 UTC, FarhanMobashir approved these changes
All good ✅ now

2022-02-12 12:50 UTC, bhanuprakashj reviewed
looks good to me!!

2022-02-12 12:56 UTC, merged